# This is a config for E2B sandbox template.
# You can use template ID (r0ktcfydo2z8dvq3daqj) or template name (vibe-nextjs-test-sid-1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs-test-sid-1") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-sid-1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-sid-1')

team_id = "afcd0851-b864-49fd-9c71-5f583184f057"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-sid-1"
template_id = "r0ktcfydo2z8dvq3daqj"
